-- in case migrations fail, the naming convention failed
create table if not exists tableZ (
    id smallint generated by default as identity primary key,
    code char(4) not null,
    description text not null default 'table Z',
);